config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root "home#index"

  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_3a7310d375db41c0b79a78a220cfee4d')
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<center>Copyright (C)Kentaro Namerisawa </center>

app/views/home/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to "StockAnalysis", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link" %>
        </li>
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>Stock is... </p>

app/views/home/index.html.erb
<h1>Stock Analysis</h1>
<p>What are you gonna do for your stock?!</p>

<% stock = StockQuote::Stock.quote("fb") %>
<%= stock.latest_price %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Stock Market</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "home/navbar" %>
    <br>
    <div class ="container">
    <%= yield %>
    </div>
    <%= render "home/footer" %>
  </body>
</html>